version: '3.8'

services:
  yellow-media-app:
    build:
      context: .
      dockerfile: docker/nginx/1.23/Dockerfile
      args:
        - NGINXUSER=${NGINXUSER:-www-data}
        - NGINXGROUP=${NGINXGROUP:-www-data}
    container_name: yellow-media-app
    ports:
      - '${APP_PORT:-80}:80'
    volumes:
      - .:/var/www/html:delegated
    depends_on:
      - yellow-media-php
    networks:
      - yellow-media

  yellow-media-php:
    build:
      context: .
      dockerfile: docker/php/8.1/Dockerfile
      args:
        - PHPUSER=${PHPUSER:-www-data}
        - PHPGROUP=${PHPGROUP:-www-data}
    container_name: yellow-media-php
    user: ${PHPUSER:-www-data}
    volumes:
      - .:/var/www/html:delegated
    networks:
      - yellow-media

  yellow-media-db:
    image: 'postgres:14'
    container_name: yellow-media-db
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - yellow-media-db-volume:/var/lib/postgresql/data
    networks:
      - yellow-media
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]
      retries: 3
      timeout: 5s

networks:
  yellow-media:
    driver: bridge

volumes:
  yellow-media-db-volume:
    driver: local
